version: "3.9"

services:
  scalesecret:
    build: .
    image: scalesecret:${TAG}
    container_name: scalesecret
    network_mode: host # or bridge or whatever your network is
    pull_policy: never
    environment:
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - CHAT_ID
      - OWNER_ID
      - GEMINI_API_KEY

  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    # This command will restart the 'scalesecret' container every 50 hours.
    command: ["/bin/sh", "-c", "while true; do sleep 180000; docker restart scalesecret; done"]
    restart: unless-stopped
    network_mode: host

networks:
  default: 
    external: true
    name: host
